import Config

# Note we also include the path to a cache manifest containing the digested
# version of static files. This manifest is generated by `mix phx.digest`,
# run during `mix assets.deploy` before the release is assembled.
config :beam_campus_web, BeamCampusWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# TLS is terminated by Caddy in front of the release; force_ssl only needs to
# honour the proxy's X-Forwarded-Proto. `localhost`/`127.0.0.1` are excluded so
# the in-container healthcheck (curl http://localhost:4000/health) is not
# redirected to https.
config :beam_campus_web, BeamCampusWeb.Endpoint,
  force_ssl: [rewrite_on: [:x_forwarded_proto], exclude: ["localhost", "127.0.0.1"]]

# Swoosh: use the Req API client, disable local memory storage.
config :swoosh, :api_client, Swoosh.ApiClient.Req
config :swoosh, local: false

# Do not print debug messages in production.
config :logger, level: :info

# Runtime production configuration (env vars) lives in config/runtime.exs.
